### ISSUE TITLE
is it possible to play Spotify full-length track in background with this Plugin ?

### ISSUE THREAD

**Issue by Sk4nDev** [Festify/cordova-spotify#19]
Hello :)
i would like to ask if this plugin supports audio player, or is it just a plugin to fetch information from spotify ? cuz i'm planning to make a music player app for Android/IOS with possibilty to play the tracks in BG,
and will u share a documentation or some tutorials/exemples ?
THANKS

**Comment by NeoLegends** [comment]
Please see the readme. It contains all the information you need: https://github.com/Festify/cordova-spotify/blob/develop/README.md

**Comment by mraerino** [comment]
Actually there was a bug with this, which we just fixed.
(See https://github.com/Festify/cordova-spotify/commit/00c2569170609f9a3c3b601ed2607fc574456d28)

We will release this soon.
