### ISSUE TITLE
Logout functionality

### ISSUE THREAD

**Issue by NeoLegends** [Festify/cordova-spotify#20]
Currently it's not possible to log out once logged in.

**Comment by tadowns** [comment]
As mentioned in another issue: If a user has to re-authenticate with spotify we will get "An instance of SPAudioStreamingController is already in use". It is probably safe to assume the logout implementation will allow us to work around this.

**Comment by leolabs** [comment]
Yes, that is correct.

**Comment by NeoLegends** [comment]
Hey @tadowns!

We just rewrote the plugin to _only_ focus on playback. The plugin itself has become stateless - meaning that there is no notion of one being "logged in" or "logged out". One simply provides a valid access token every time a track shall be played and the plugin handles the rest.

Authentication has to be done manually now, but we think about providing a separate plugin just for that. :)

----

This ticket has become irrelevant, closing.
