### ISSUE TITLE
An instance of SPAudioStreamingController is already in use w/ expired token?

### ISSUE THREAD

**Issue by tehg00se** [Festify/cordova-spotify#22]
Great plugin first of all.  After some finicky stuff with my own .env I'm able to authenticate and stream/pause music without any issue.

The only issue I run into is when the token expires.  Going through my server logs (PHP), I see that the request makes it, but it dies before it gets a response with an updated token telling me that an instance of SPAudioStreamingController is already in use.

I tried details documented in https://github.com/Festify/cordova-spotify/issues/14

I'm working from the latest development branch, and the nightly builds (which I understand are unstable, and that this plugin is in beta).

If login fails, I can obviously reauthenticate with Spotify in the error callback.  Is there any way to refresh the users' token without having to fully reauthenticate, once their token has expired?

Initial Authentication Script:
` try {
                  cordova.plugins.spotify.login({
                      clientId: 'DUMMY-DI',
                      tokenRefreshUrl: "http://example.com/refresh"
                  }).then(function(session){
                      this.authenticateWithSpotfy = false;
                      this.session = session;
                  }).catch(function(error){
                      console.error("There was an error during the login process : " + JSON.stringify(error));
                      try {
                          cordova
                              .plugins
                              .spotify
                              .authenticate(params)
                              .then(session => {
                                  this.authenticatingWithSpotify = false;
                                  this.session = session;
                              })
                              .catch(function(error){
                                  this.authenticatingWithSpotify = false;
                                  console.error("ERROR AUTHENTICATING : " + JSON.stringify(error));
                              });
                      }
                      catch(e) {
                          console.error("Caught Authentication error " + JSON.stringify(error))
                      }
                  })
          } catch (e) {
             console.log("Caught Login error " + JSON.stringify(error));
          }`

**Comment by NeoLegends** [comment]
Uh, thanks for reporting this! The Spotify docs weren't really clear on how to deal with expired access tokens. The iOS SDK refreshes it's token itself, the android one doesn't, etc. We will definetely have to improve on that front.

**Comment by tehg00se** [comment]
Hey thanks for the reply @NeoLegends 

Thanks for the clarification on the session refresh, no worries there; all works as expected.

I know the track length is available over the web-api, however, I've added in the functionality to return the track duration in MS into the iOS portion of the plugin (haven't done much testing on Android yet).  I'm going to be adding in a seek position function as well in the next few days to set the playBack state to a specific ms in the song.

I can commit these updates if you'd like; they're iOS only right now, but I'll be working on doing Android later.  Let me know if you're okay with that

**Comment by NeoLegends** [comment]
Hey!

We'd probably leave out the duration functionality (*), but the seeking stuff would be much appreciated! Please send in a PR once you've got everything working on iOS and Android. :) that would be awesome. 

(*): We wanna favor the Web API because we feel that the web API is more stable than the native SDKs and will be there for a longer time than the SDKs. If you look at what happened with libspotify, you'd favor the Web API, too. ;) especially since it returns the exact same data as the SDKs.

**Comment by tehg00se** [comment]
Ha yeah I read a little bit about libspotify, particularly the part where they just decided to "shut it down" without telling anyone.

It makes me wonder what their future plans are for the SDK now that they've opened up playback over the web API.
