### ISSUE TITLE
Some starter docs

### ISSUE THREAD

**Issue by Remco75** [Festify/cordova-spotify#23]
I am currently building a cordova app, and definitely am gonna see if I can get this to work!
I already have the token exchange API, but are there some basic readme or starter docs ?

Would be really nice!
I am of course willing to expend them with my experiences with the plugin :-)

**Comment by NeoLegends** [comment]
Hey!

Right now there are no real docs, as this plugin hasn't stabilized yet, and we wanted to save the effort of writing docs and keeping them up-to-date for when 1.0 is ready. :)

The public interface is extremely simple, though. Just look at `www/cordova-spotify.js`. That's all there is. All methods return promises.

**Comment by NeoLegends** [comment]
Closing this because there really isn't anything else to discuss! 🙌

**Comment by NeoLegends** [comment]
Remark for future readers: we now have API documentation in the readme. :)
