### ISSUE TITLE
authenticate missing paramaters

### ISSUE THREAD

**Issue by ghost** [Festify/cordova-spotify#24]
Hi! Thanks a lot for providing this library!

I'm trying to call the authenticate method by passing in the object with the required fields.

My object looks like this:

`options = {
          clientId: '4d0...333',
          redirectUrl: 'http://random.com/callback',
          scopes: ['playlist-read-private'],
          tokenSwapUrl: 'http://cloudfunctions.com',
          tokenRefreshUrl: 'http://cloudfunctions.com'
 }`

But when I run spotify.authenticate(options) I get the error "Missing parameters!". I've been looking at [this](https://github.com/Festify/cordova-spotify/blob/develop/www/platforms/ios.js) and can't figure out what I'm doing wrong. 

Thank you!

**Comment by NeoLegends** [comment]
There doesn't seem to be anything wrong with the code you provided on first sight. Maybe a more detailed (and more complete) example will provide better insight into what's happening exactly. 

You could also try using a debugger to step through the code as it's running. You can use either Safari (for iOS) or Chrome (for Android) as a remote debugger.

**Comment by ghost** [comment]
Got it working! I downloaded it using the GitHub link instead of `cordova-spotify`. I'm not sure if that made a difference. Thanks for the help anyways!

**Comment by NeoLegends** [comment]
But you did install the plugin via "cordova plugin install ..."?

**Comment by NeoLegends** [comment]
Also check your package-lock.json. We've had troubles with cordova and the new lockfile npm generates since v5. Could be that you're actually still running an old version of the plugin (v0.3). I did some variable renaming in v0.4, which might be causing your problems.

**Comment by ghost** [comment]
Yeah, I did "cordova plugin install". It could have been the package-lock.json. Now it looks like this:

`"cordova-spotify": {
      "version": "git+https://github.com/Festify/cordova-spotify.git#386aed77cef2c4545c22c4f888c4d1247962292d"
    },`

It's working now!
