### ISSUE TITLE
Universal links support

### ISSUE THREAD

**Issue by NeoLegends** [Festify/cordova-spotify#26]
Right now we only support custom protocols as a way to finish the authentication, but universal links are the new shiny way to do in-app-redirects. We should support them.

**Comment by Remco75** [comment]
Are there any plans on implementing this? I am kinda stuck on Ios with this....
I use the ionic-deeplink-plugin
https://github.com/ionic-team/ionic-plugin-deeplinks to handle deeplinks
But on iOs the return from the browser keeps hanging, prob the same issue as #25 ...
Any suggestions how to fix this  using this deeplink plugin?

**Comment by NeoLegends** [comment]
Yeah we're going to need that ourselves very soon. This is on our list.

**Comment by Remco75** [comment]
Cool, can I do anything to help out? I will dive into the code and see what I can find (not a C programmer, so bear with me... ;-)

Do you guys have any Idea to tackle this already?

**Comment by NeoLegends** [comment]
Closing this due to the 0.5.0 rewrite.
