### ISSUE TITLE
Playback returns "The operation failed due to an unspecified issue."

### ISSUE THREAD

**Issue by ghost** [Festify/cordova-spotify#27]
Hey, sorry for all the questions. 

I've got all the authentication working now! Thank you for that. My last issue is with playback. I'm trying to play a track using the session variable that is returned to me after logging in. The session object looks like this:

<img width="267" alt="screen shot 2017-07-10 at 5 32 37 am" src="https://user-images.githubusercontent.com/12905197/28012045-8a49b636-6532-11e7-8f0e-804fdcb7f333.png">

When I call `this.session.play('spotify:track:6rPO02ozF3bM7NnOV4h6s2')` it returns this error:
<img width="321" alt="screen shot 2017-07-10 at 5 32 48 am" src="https://user-images.githubusercontent.com/12905197/28012072-ac04858a-6532-11e7-98a4-6df5a649ff1e.png">

I used the debugger tool to find where I think it's coming from: 
**Never mind!**
<img width="694" alt="screen shot 2017-07-10 at 5 48 24 am" src="https://user-images.githubusercontent.com/12905197/28012337-73b63e52-6533-11e7-93df-99822c858510.png">

When I step though the debugger it returns **here**:
<img width="1440" alt="screen shot 2017-07-10 at 5 58 55 am" src="https://user-images.githubusercontent.com/12905197/28012790-e945b836-6534-11e7-8747-59625221d2f5.png">

I see from [this page](https://github.com/spotify/ios-sdk/blob/master/SpotifyAudioPlayback.framework/Headers/SPTAudioStreamingController_ErrorCodes.h) that the error pops up due to 
`
/** The operation failed due to an unspecified issue. */
FOUNDATION_EXPORT NSInteger const SPTErrorCodeFailed;
`
Am I implementing the play feature incorrectly? What should I do to resolve this problem? 

I've been trying to follow your code from [here](https://github.com/Festify/app/blob/a49b6eae45dd705f8d6ea059b57d99a79eef7f42/elements/providers/playback/playback-spotify.html)

`
play(ref) {
  return this._withSession(s => s.play(ref ? 'spotify:track:' + ref.id : ref), () => Promise.reject());
}
`

Thanks again for the help!

**Comment by NeoLegends** [comment]
That is super weird.

Seems like there are issues with the native side of the plugin. We (Festify Dev Team) will be meeting up for further development likely next week, so we might take a look at this. In the meantime, you could try running your App with the XCode debugger attached (load the cordova project files with XCode and hit play) and step through the native code there. Might yield some more insights. :)

**Comment by ghost** [comment]
Figured it out! Lol... needed to add streaming to my scopes. They should throw a better error for that haha. Thanks for all the help!

**Comment by NeoLegends** [comment]
Ah well! Good to know it's working for you. I'm gonna close this then. :)
