### ISSUE TITLE
Move to native storage

### ISSUE THREAD

**Issue by Remco75** [Festify/cordova-spotify#28]
Currently the plugin uses localstorage to store it's stuff.
But there are some limitations to that: one being that iOS tends to flush localStorage when it runs out of memory.
Maybe a better solution would be this: 
https://github.com/TheCocoaProject/cordova-plugin-nativestorage

**Comment by NeoLegends** [comment]
Thanks for the suggestion! This one should be easy to ship soon. We'd also be happy if you PR'd that functionality in.

**Comment by Remco75** [comment]
ok, I will try to make a PR sometime this week!

**Comment by NeoLegends** [comment]
Hey @Remco75!

For 0.5.0 we rewrote the plugin to _only_ focus on playback (and leave login to something else). This feature request is not relevant anymore. :)
