### ISSUE TITLE
Need help on debugging:

### ISSUE THREAD

**Issue by Remco75** [Festify/cordova-spotify#30]
Strange problem , hope someone can help me out. 
The plugin works fine in the beta-track in the play store: so nice job :-)

But I can't get it to work on my emulator (anymore).
This used to work, but after some installing / reinstalling / removing data is does not work anymore.
All I get back is a error which says: wrong response, Type: error.

Has anyone seen this before?

**Comment by NeoLegends** [comment]
This is likely related to a missing or wrong "Content-Type"-header during the authentication process. The cloud function cannot parse the request body. Spin up a debugger attached to the cordova app (or the cloud function) and check whether the requests have the right content type header.

**Comment by Remco75** [comment]
it does not even get to the point where it makes requests: no request in chrome-devtools anyway...

**Comment by NeoLegends** [comment]
iOS or Android?

**Comment by Remco75** [comment]
android

**Comment by NeoLegends** [comment]
Hmm, this is super weird. Could you attach a debugger to the plugin anyway and check where it breaks? Could there be some cache interfering with the HTTP requests so that they don't appear in the debugger?

**Comment by Remco75** [comment]
yeah, I will try to dig deeper. Even If i install the signed apk that runs in play-store it does not work. So it must be the env I guess

**Comment by Remco75** [comment]
I Am not a JAVA programmer, so I really wouldn't know how to attach a debugger to this process. 
But the only place where this error gets thrown is in rule-nr 271 of CordovaSpotify.java: 
Extracted form the onLoginResult method:
` if (response.getType() != AuthenticationResponse.Type.CODE) {
            cb.error("Wrong response type: " + response.getType().toString());
        } '
So what I can make of it without debuggers:
is does get some kind of valid activityResult , but calling  AuthenticationClient.getResponse makes it fail.

To make things even weirder (but somehow also consitent) this happens also on a real device. Installing the beta from the store: works like a charm. 
Deploying the build apk: nope...

**Comment by NeoLegends** [comment]
We'll do another hack-day on sunday, I'll note this down on the agenda. Could be a bug or at least something where we can make the plugin more fault-tolerant.

**Comment by Remco75** [comment]
cool , I will keep looking, If i find anything I will let you know

**Comment by Remco75** [comment]
Some more info: Calling the authenticate function does trigger a webview from spotify ( is see it appearing in dev-tools in the remote device section, but i never switches to it. (so it does not become visible).

Also the spinner when connecting to spotify does appear for a while

**Comment by Remco75** [comment]
Ok, I got the project running in android studio :-)
Setting a breakpoint in line 270 of CordovaSpotify reveals that the response objects contains the property 'mError' saying: INVALID_APP_ID... 

Revealing my incredible stupidiy.... I accidentally deleted the develop keyHash from the spotify-my-app section. 

So this one can be closed! sorry :-(
Although some less cryptic errors would be nice. At this point, the plugin returns just: `wrong response Type: error` regardless of what goes wrong....

Giving back the actual error in the mError property would save time in the future

**Comment by NeoLegends** [comment]
Ahh! Great, yeah we'll improve on that.
