### ISSUE TITLE
Pause, resume, playFromPosition

### ISSUE THREAD

**Issue by Remco75** [Festify/cordova-spotify#34]
This is prob more a feature request:

Would be really nice to be able to pause playback and resume from that position.

Simple method would be to store the position when pausing the track, but it would mean we need to be able to play a track starting at a specified position. The SDK should support it, but this plugin not yet as far as i can see.

Any plans on supporting this?

**Comment by NeoLegends** [comment]
It already is! Just pass `null` for the track ID and the player will resume the currently loaded track.

**Comment by Remco75** [comment]
thats cool! missed that one. Still it would be nice to start at any given position.... So we can skip through tracks with a slider-like component?

what do you think?

**Comment by NeoLegends** [comment]
Yeah, this would be a nice-to-have.

Festify, however, does not need it, so I'm not sure when we'll ever come around to implement that. PRs definetely welcome on this. :D

**Comment by NeoLegends** [comment]
Oh btw, the v0.5.0 rewrite has this functionality. :)
