### ISSUE TITLE
Can't figure out how to play song

### ISSUE THREAD

**Issue by ryantrappy** [Festify/cordova-spotify#36]
First off this plugin looks like it is exactly what I need, but I can't seem to truly figure out how it is used. It would be awesome if there was an example application that someone could look at and figure out how to use the plugin.  

`
            var events = spotifySession.getEventEmitter();

            spotifySession.getEventEmitter().then( function(data){
                console.log("got event emitter");
                console.log(data);
            });

            spotifySession.play(trackInfo.track.uri, {
                token:$scope.spotifyAuthToken,
                "clientId":client_ID
            }).then(
                function(data){console.log(data)},
                function(data){console.log(data)}
                );
`

The app is an ionic app and at this point in the code I have already authenticated with OAuth. The event emitter that is printed is a promise but has no events emitted out of it and no sound plays. Any direction provided would be greatly appreciated.

**Comment by NeoLegends** [comment]
This is exactly how the plugin is supposed to be used. Does the plugin return any specific error in the promise or do you instantly get an error thrown when calling the methods?

Are you on Android or iOS? Could you post some console logs (either native, via Android / iOS Debugger, or from the web context via Chrome Debugger or Safari Debugger)? This would help identifying the issue.

**Comment by ryantrappy** [comment]
Since it ionic, it is both android and iOS but I am testing on iOS currently. 
<img width="367" alt="screen shot 2017-10-16 at 12 47 41 pm" src="https://user-images.githubusercontent.com/11083022/31626671-411dbf12-b270-11e7-9068-dbece1cbf167.png">

Here is an output of the event emitter and the error I get. I am not sure why it thinks I am passing the wrong username/password as I am passing the actual auth token.  I looked at #27 and their event emitter had all the possible events and other events but mine does not have any of that. Are these two related?

**Comment by NeoLegends** [comment]
No. Wrong username / password indicates the token you supplied is invalid. Are you sure you‘re passing in a valid one with the required scopes („streaming“ in this case)?

**Comment by NeoLegends** [comment]
The event emitter is not related to the login btw. You can login without getting an event emitter first.

**Comment by ryantrappy** [comment]
That fixed it! Thank you very much. I read in another issue about required scopes but it just clicked that that meant spotify requested scopes and not the scope of the app.

**Comment by NeoLegends** [comment]
Spotify does request OAuth scopes! (Remember, this is not your angular scopes, OAuth scopes represent the capabilities of the auth token).

Our Spotify OAuth plugin is specifically designed to prevent invalid-token-errors by automatically refreshing the token whenever needed. See here: https://github.com/Festify/cordova-spotify-oauth.
