### ISSUE TITLE
demo code

### ISSUE THREAD

**Issue by rijink7** [Festify/cordova-spotify#37]
Could you please provide sample code to try this plugin. thanks in advance

**Comment by NeoLegends** [comment]
Right now we‘re short on time. But please take a look at the question part of https://github.com/Festify/cordova-spotify/issues/36, it shows how the plugin is supposed to be used. It‘s really that simple. Just call one function to play a track.

**Comment by NeoLegends** [comment]
~~Also take a look at our API Documentation ovef here https://github.com/Festify/cordova-spotify/blob/develop/README.md#api-docs.~~

 I‘m going to rewrite the JS part in TypeScript soon, so that we have real, auto-generated API docs.

**Comment by NeoLegends** [comment]
TS rewrite is done, new documentation can be found here: https://festify.github.io/cordova-spotify/.

**Comment by rijink7** [comment]
thanks @NeoLegends it was really helpful,.
