### ISSUE TITLE
Build fails with "Could not find :spotify-sdk:"

### ISSUE THREAD

**Issue by psamsotha** [Festify/cordova-spotify#38]
* **Cordova:** 8.0.0
* **Gradle**: 4.1
* **Android:** 8.0 SDK Platform 26
* **OS**: Mac 10.13.1

**Reproduce:**

```
cordova create testapp
cd testapp
cordova platform add android
cordova plugin add cordova-spotify
cordova build android
```

When building I am getting the following build error

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
Could not find :spotify-sdk:.
Searched in the following locations:
   file:/<home>/Library/Android/sdk/extras/m2repository//spotify-sdk//spotify-sdk-.pom
   file:/<home>/Library/Android/sdk/extras/m2repository//spotify-sdk//spotify-sdk-.aar
   file:/<home>/Library/Android/sdk/extras/google/m2repository//spotify-sdk//spotify-sdk-.pom
   file:/<home>/Library/Android/sdk/extras/google/m2repository//spotify-sdk//spotify-sdk-.aar
   file:/<home>/Library/Android/sdk/extras/android/m2repository//spotify-sdk//spotify-sdk-.pom
   file:/<home>/Library/Android/sdk/extras/android/m2repository//spotify-sdk//spotify-sdk-.aar
   https://jcenter.bintray.com//spotify-sdk//spotify-sdk-.pom
   https://jcenter.bintray.com//spotify-sdk//spotify-sdk-.aar
   https://maven.google.com//spotify-sdk//spotify-sdk-.pom
   https://maven.google.com//spotify-sdk//spotify-sdk-.aar
   https://repo1.maven.org/maven2//spotify-sdk//spotify-sdk-.pom
   https://repo1.maven.org/maven2//spotify-sdk//spotify-sdk-.aar
   file:/<project>/platforms/android/app/libs/spotify-sdk-.aar
   file:/<project>/platforms/android/app/libs/spotify-sdk.aar
Required by:
   project :app
```

I'm not sure if it is a problem with Cordova or with this cordova-spotify.  I know the Spotify Android SDK docs says that the project is in beta and that things may be changing. I don't know if this problem has something to do with a recent change or not. Or maybe a problem with the paths (I noticed double slashes - not sure if that's correct or not).

**Comment by NeoLegends** [comment]
Hmm, as you can see here https://github.com/Festify/cordova-spotify/blob/0f610e6cf4d4b0a169214dabe9f978b04e5a9af9/src/android/build.gradle#L9, we're just importing the SDK from maven central. We're not too familiar with maven, so maybe there's an issue with them?

**Comment by psamsotha** [comment]
After some playing around, I think I found the problem. From [Cordova Android 7.0.0 Released!][release], it's saying that the project structure for Android projects has changed.

Here's what's happening.

1. In the plugin.xml, there's a pre-install hook that downloads the archive straight from the Spotify repo and adds it the `SDK_INSTALL_PATH`

    **plugin.xml**

       <hook type="before_plugin_install" src="install-android.sh" />

    **install-android.sh**

       SDK_INSTALL_PATH="plugins/cordova-spotify/src/android/spotify-sdk"
       SDK_DOWNLOAD_PATH="https://github.com/spotify/android-sdk/archive/24-noconnect-2.20b.tar.gz"

       if [ ! -d "$SDK_INSTALL_PATH" ]; then
           mkdir -p "$SDK_INSTALL_PATH"
           curl -LsS $SDK_DOWNLOAD_PATH | tar -xz -C "$SDK_INSTALL_PATH" --strip 1
       else
           echo "Skipping streaming SDK download since it's alredy there."
       fi

2. Also in the plugin.xml, there is an instruction to copy that downloaded archive into the android project

       <resource-file
            src="src/android/spotify-sdk/spotify-player-24-noconnect-2.20b.aar"
            target="libs/spotify-sdk.aar" />

3. Based on the build.gradle, Gradle looks for that copied file

        repositories {
            flatDir {
                dirs 'libs'
            }
        }
        dependencies {
            compile(name:'spotify-sdk', ext:'aar')
        }

And I think this is the discrepancy between the current version and previous version builds. If you look at the error message above, you'll see Gradle is looking for the file at the following location

    file:/<project>/platforms/android/app/libs/spotify-sdk.aar

but the `resource-file` directive copies it to 

    file:/<project>/platforms/android/app/src/main/libs/spotify-sdk.aar

I guess this is where "resources" are supposed to go, in the `src/main`. Maybe in the previous version builds, Gradle would look here. I'm not sure as I just started using Cordova and the latest version is the only version I have ever really used.

I looked at some other plugins, and saw that they will use the `source-file` instruction to copy the archive files, but moving the file location wouldn't be backward compatible. So what we can do is just add the `src/main/libs` to the build.gradle to tell Gradle to also look there

    repositories {
        flatDir {
            dirs 'libs', 'src/main/libs'
        }
    }

I tested this out and it works. I made a [PR][pr] to resolve this.



[release]: https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html
[pr]: https://github.com/Festify/cordova-spotify/pull/39

**Comment by pontigol** [comment]
Hi,

I still get the error above. Checked my cordova-spotify version (newly installed) and it said 0.5.0 so I figured I had an old installation. Tried to add...
````
repositories {
    flatDir {
        dirs 'libs', 'src/main/libs'
    }
}
````
...manually but it didn't work. I then tried to install the latest develop branch where above error is supposedly fixed but I get an error on install. What am I doing wrong? Would very much appreciate help on this.

@rijink7 Did you have any success installing it eventually?

Best regards,
Pontus

**Comment by psamsotha** [comment]
@pontigol Yeah I just tested it again by just [following my reproduce instructions][1] and then just changing the `build.gradle` by adding the `'src/main/libs'`, and it didn't work. Not sure why it worked when I made the PR. I'm sure that I narrowed down the problem to _this_. I have not worked with Cordova since the last project where I was using this dependency, so I forgot a lot of what I learned while solving this issue. But just to get the build working, if you want to manually make the changes, what you can do is just copy

    <project>/platforms/android/app/src/main/libs/spotify-sdk.aar

to 

    <project>/platforms/android/app/libs/spotify-sdk.aar

I have just tested this right now, and the build was a success. I did not test the app though to see if it is working.


[1]: https://github.com/Festify/cordova-spotify/issues/38#issue-285021021

**Comment by pontigol** [comment]
Brilliant, thank you! At least the build was successful, I will try if it works soon. Thanks again.
