### ISSUE TITLE
[Help needed] Example of getEventEmitter usage

### ISSUE THREAD

**Issue by pontigol** [Festify/cordova-spotify#42]
Hi,

If anyone could provide a simple example of how to use getEventEmitter, that would be very appreciated! For example, how to obtain the eventemitter and get an emitted playbackevent.

I have have no prior experience with eventemitter3. 

Thanks!

Pontus

**Comment by NeoLegends** [comment]
https://festify.github.io/cordova-spotify/ This is the API documentation. It contains all the information you need. Reading the eventemitter3 docs will also help. The emitter from eventemitter3 really is a standard implementation, using `.on`, `.once`, etc.

**Comment by pontigol** [comment]
Thanks, I read the cordova-spotify docs but it seemed to me the eventemitter didn't work quite the same as the other functions (play, pause etc), at least I didn't get it to work. I will read the eventemitter docs more thoroughly and see if I understand it. I realize that this repo is not very active anymore, but if anyone would just stumble upon an example using the getEventEmitter in cordova-spotify that would really sort things out for me. 

Another stupid question: is the eventemitter3 included in cordova-spotify or do I need to include it separately?

**Comment by NeoLegends** [comment]
> Thanks, I read the cordova-spotify docs but it seemed to me the eventemitter didn't work quite the same as the other functions (play, pause etc), at least I didn't get it to work.

What did you try? :) I'll just give you something here real quick:

```js
cordova.plugins.spotify.getEventEmitter()
    .then(emitter => {
        emitter.on('playbackevent', eventName => {
            switch (eventName) {
                case 'PlaybackEventAudioFlush': console.log("Audio flushed"); break;
                case 'PlaybackNotifyPause': console.log("Playback was paused"); break;
                default: console.log("Some other event was thrown:", eventName); break;
            }
       });
    });
```

> I realize that this repo is not very active anymore, but if anyone would just stumble upon an example using the getEventEmitter in cordova-spotify that would really sort things out for me.

Yeah it's not that active anymore, but it should still work. :) If there are any issues we're eager to fix them, because this is the only cordova spotify library that works on both Android and iOS and we'd like to keep it that way.

> Another stupid question: is the eventemitter3 included in cordova-spotify or do I need to include it separately?

Yeah, it's already included for you.

**Comment by pontigol** [comment]
Oh, thank you so much, this is very helpful! I think I misunderstood the whole emitter concept (would be embarrassing to post what I tried :)) but now it got a lot clearer. Will test this in my own code later today.

Also thanks for the other clarifications. And yes, I already got the rest to work like a charm, so I am very grateful this plugin is alive and kicking.

Best regards,
Pontus

**Comment by NeoLegends** [comment]
Great!

I updated the readme and issued a new npm release with some other small bugfixes.
