### ISSUE TITLE
Failing to build.

### ISSUE THREAD

**Issue by noobiept** [Festify/cordova-spotify#43]
Hello, the plugin is failing to build at the moment, it seems like its due to a change from spotify.

The download URL isn't available anymore: https://codeload.github.com/spotify/android-sdk/tar.gz/24-noconnect-2.20b

https://github.com/Festify/cordova-spotify/blob/develop/install-android.sh#L4

**Comment by oliversalzburg** [comment]
See https://developer.spotify.com/community/news/2018/09/14/updates-mobile-platform/ for details

**Comment by oliversalzburg** [comment]
The old SDK has been moved to: https://github.com/spotify/android-streaming-sdk

**Comment by noobiept** [comment]
Old link still here: https://github.com/spotify/android-streaming-sdk/releases

But probably better to think about using the newer SDK.

**Comment by NeoLegends** [comment]
Workedaround in 2d7bea9f801ea4fe4c8804955647e3290736d236.

For the time being I fixed the SDK paths. However, as we're not using this actively anymore, the plugin probably receives less maintenance than it should. Therefore I am asking: is anybody willing to take over maintenance of the plugin? I would add her / him as contributor here for push access.

**Comment by noobiept** [comment]
Sure you can add me, I'm using this on my job atm.

**Comment by NeoLegends** [comment]
> Sure you can add me, I'm using this on my job atm.

Great! Speaking of which, could you send some changes as PR before I add you here? :)
