### ISSUE TITLE
Refresh token.

### ISSUE THREAD

**Issue by tarun57** [Festify/cordova-spotify#51]

**Comment by tarun57** [comment]
I'm using spotify api and am not able to login in spotify from ionic app after token expired.
So how can i get refresh token.

**Comment by NeoLegends** [comment]
Not through this plugin, because this plugin doesn't concern itself with authentication (by design, see the readme of this plugin for more information). You need to do this yourself, or use our other library, https://github.com/Festify/cordova-spotify-oauth.
