### ISSUE TITLE
Read library content

### ISSUE THREAD

**Issue by Defcon0** [Festify/cordova-spotify#52]
Hello,

I try to read the spotify library for an importer into my own app. Is this already possible with this plugin or if not maybe a cool feature for the future?

Bye

**Comment by NeoLegends** [comment]
This library is solely concerned with playback (by design), for metadata-related things we recommend the Web API :)

**Comment by NeoLegends** [comment]
See https://developer.spotify.com/documentation/web-api/ for more information. The web API also provides access to the user's library.
