### ISSUE TITLE
Not able to play Podcast Episode

### ISSUE THREAD

**Issue by tylerpashigian** [Festify/cordova-spotify#53]
I am trying to use this plugin to play a Spotify podcast episode rather than a song with the following code.

`cordova.plugins.spotify.play("spotify:episode:3rY1aNlsNfWCpt90BQ9Qth", {
      clientId: "myClientId",
      token: this.token
    })`

I am getting the error for non premium users: "login_failed: Spotify Premium Required". Non premium users are still able to listen to individual podcast episodes, so I expected this to work. Is this a limitation of the Spotify SDK or is this an issue?

**Comment by NeoLegends** [comment]
The streaming SDK only works for premium users unfortunately.
