### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mowaiskalam** [Festify/cordova-spotify#8]
I have installed 'npm webpack' then add this plugin i am getting error: Output filename not configured.

![image](https://cloud.githubusercontent.com/assets/17184822/22420480/62dcc4f0-e704-11e6-9683-cf1f4173c737.png)

**Comment by NeoLegends** [comment]
Thanks for the report!

I have a feeling what it could be but could you give us more of the console output?

**Comment by mowaiskalam** [comment]
Thank you @NeoLegends for your reply. Here is the complete output:

![image](https://cloud.githubusercontent.com/assets/17184822/22427647/d414df9c-e725-11e6-9f79-481faaf5d806.png)
![image](https://cloud.githubusercontent.com/assets/17184822/22427655/db0bcf04-e725-11e6-9ccb-d6c796d8c4de.png)
![image](https://cloud.githubusercontent.com/assets/17184822/22427661/de89424c-e725-11e6-8c71-6c3cc25e5535.png)

**Comment by mowaiskalam** [comment]
Also @NeoLegends can u please describe me basic level of documentation after successful installation because i am using this plugin in VS cordova option and i am unable to add but i don't know how to use it or what it's basic method or class ? It will be helpful for me. Thank you

**Comment by NeoLegends** [comment]
It seems like your project path contains spaces. As it says in the readme, project paths with spaces are not supported. Please try the installation again from a folder without any spaces in it.

 

Von: Muhammad Owais Kalam [mailto:notifications@github.com] 
Gesendet: Montag, 30. Januar 2017 15:54
An: Festify/cordova-spotify <cordova-spotify@noreply.github.com>
Cc: Moritz Gunz <moritz.gunz@gmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [Festify/cordova-spotify] Installation Issue (#8)

 

Thank you @NeoLegends <https://github.com/NeoLegends>  for your reply. Here is the complete output:

 <https://cloud.githubusercontent.com/assets/17184822/22427647/d414df9c-e725-11e6-9f79-481faaf5d806.png> 
 <https://cloud.githubusercontent.com/assets/17184822/22427655/db0bcf04-e725-11e6-9ccb-d6c796d8c4de.png> 
 <https://cloud.githubusercontent.com/assets/17184822/22427661/de89424c-e725-11e6-8c71-6c3cc25e5535.png>

**Comment by NeoLegends** [comment]
It seems like your project path contains spaces. As it says in the readme, project paths with spaces are not supported. Please try the installation again from a folder without any spaces in it.

API Documentation will follow later, once the plugin is production ready and the APIs have settled. For the moment, the plugin is available under `cordova.plugins.spotify`. You can create a new Spotify session via `cordova.plugins.spotify.authenticate(params)`. `params` is an object, please refer to https://github.com/Festify/cordova-spotify/blob/develop/www/cordova-spotify.js#L35 to see what information you need to provide. The function returns a promise that resolves to the session object once the authentication process is completed.

**Comment by mowaiskalam** [comment]
@NeoLegends am i doing something wrong ? :( My Project does not have any space at all. I have placed project on drive root and add plugin still i am facing this issue.

**Comment by NeoLegends** [comment]
Could you give me the output again (as text cp'd from the console, not as screenshots)?

**Comment by mowaiskalam** [comment]
Here you go:

`Fetching plugin "https://github.com/Festify/cordova-spotify.git" via git clone
Repository "https://github.com/Festify/cordova-spotify.git" checked out to git ref "master".
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\build-extras.gradle

cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\build-extras.gradle
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-android.sh

cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\build-extras.gradle
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-android.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-ios.sh

cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\build-extras.gradle
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-android.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-ios.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\LICENSE.md

skipping existing file: .npmignore
skipping existing file: crypto.js
skipping existing file: package.json
skipping existing file: serverless.yml
skipping existing file: spotifyTokenService.js
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\build-extras.gradle
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-android.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-ios.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\LICENSE.md
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.json

cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\build-extras.gradle
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-android.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-ios.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\LICENSE.md
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.json
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.sh

cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\build-extras.gradle
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-android.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-ios.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\LICENSE.md
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.json
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\plugin.xml

cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\build-extras.gradle
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-android.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\install-ios.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\LICENSE.md
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.json
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.sh
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\plugin.xml
cp: dest file already exists: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\README.md

skipping existing file: build.gradle
skipping existing file: ConnectionEventsHandler.java
skipping existing file: CordovaSpotify.java
skipping existing file: Emitter.java
skipping existing file: PlayerEventsHandler.java
skipping existing file: AudioStreamingDelegate.h
skipping existing file: AudioStreamingDelegate.m
skipping existing file: AudioStreamingPlaybackDelegate.h
skipping existing file: AudioStreamingPlaybackDelegate.m
skipping existing file: CordovaEventEmitter.h
skipping existing file: CordovaEventEmitter.m
skipping existing file: CordovaSpotify.h
skipping existing file: CordovaSpotify.m
skipping existing file: .babelrc
skipping existing file: cordova-spotify.js
skipping existing file: const.js
skipping existing file: EventEmitter.js
skipping existing file: execPromise.js
skipping existing file: package.json
skipping existing file: android.js
skipping existing file: index.js
skipping existing file: ios.js
skipping existing file: webpack.config.js
Installing "rocks.festify.cordova-spotify" for android
Running command: C:\cygwin64\bin\bash.exe D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.sh D:\Fabu_MobileApp\Fabu_MobileApp
✨ Starting JS build

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Muhammad Owais\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.7 C:\Program Files\nodejs\node_modules\npm
Failed to install 'rocks.festify.cordova-spotify':Error: Hook failed with error code 127: D:\Fabu_MobileApp\Fabu_MobileApp\plugins\rocks.festify.cordova-spotify\package.sh
    at C:\Users\Muhammad Owais\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:230:23
    at _rejected (C:\Users\Muhammad Owais\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:844:24)
    at C:\Users\Muhammad Owais\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\Muhammad Owais\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\Muhammad Owais\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:788:41)
    at C:\Users\Muhammad Owais\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:604:44
    at runSingle (C:\Users\Muhammad Owais\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:137:13)
    at flush (C:\Users\Muhammad Owais\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\node_modules\q\q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
`

**Comment by mraerino** [comment]
Hey @mowaiskalam

Currently you need to use the plugin on a unix system (mac os / linux) or use a cygwin shell if you are on a windows system. rewriting the installation script as a JS script is on our timeline, but right now we have these requirements.

Since this plugin is beta, we don't focus on compatibility at the moment.

**Comment by mowaiskalam** [comment]
Oh @mraerino Thank you for your kind replies.

**Comment by NeoLegends** [comment]
@mowaiskalam Yeah, try it from a cygwin shell (git bash for example) and see again. Seems like `npm` isn't given the `install` command, even though it says so in the package.sh.

If that doesn't work, try removing (!) and re-adding the plugin through cordova.

**Comment by mowaiskalam** [comment]
@NeoLegends Thank you so much, now finally i have successfully installed using 'git bash' :) but now stuck in long path issue in VS. :( I will let you know i need you again. Thank you.

**Comment by mowaiskalam** [comment]
@NeoLegends I have successfully installed plugin using 'git bash' but when i am building it is giving me error about lunch activity file: here is the output on 'cordova build android'

cordova build android
Could not find launch activity in the AndroidManifest file. Can't inject Universal Links preferences.
Error: Cannot convert undefined or null to object

what am i doing wrong ?

**Comment by yheisonroa** [comment]
I have Mac but it still gives me the same problem when trying to install:

tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
